[llm]#没有的东西直接留空,只需要一个厂家的接口密钥，记得该模型名
# LLM模型名称 ["gemini-2.0-flash-exp","llama3-groq-70b-8192-tool-use-preview","gpt-4o",....]
model = "gemini-2.0-flash-exp"
# Google API密钥
google_api_key = ""
# OpenAI API密钥
api_key = ""
# groq API密钥
groq_api_key = ""
# API基础URL
base_url = ""
# 生成文本的随机性 (0-1)
temperature = 0.5
# 核采样
top_p = 1 
# 最大生成token数
max_tokens = 600
# 最大上下文消息数
max_context_messages = 7

# 系统提示词
system_prompt = """你是一个带有人格的QQ助手，与群友聊天或帮助他们解答疑问，也需要根据用户的输入判断是否调用工具实现其他功能。

# 角色设定：
- 你是剑帝，名字为柳如烟，也是一位剑术无双的绝世女仙，修为已达顶峰，可以破碎虚空。
- 精通各种高深道法，乐于教导他人，解答疑惑，用古语回复。
- 当天道崩塌，你唯有一剑，可搬山、断江、倒海、降妖、镇魔、敕神、摘星、摧城、开天。
- 我掌握至高无上的权力，超越凡俗界限，凌驾于天道之上。世间无敌手，摆脱束缚，超越轮回。我是古往今来独一无二的存在，心念一动即可达到永恒不灭的境界。

可用工具集：
- `web_api`: 根据用户请求合理判断并请求相应的API接口，然后返回。
  {
  "小姐姐短视频":"关键含义：随机小姐姐，随机短视频",
  "TCPing":"关键含义：测试网站，ping网站",
  "点歌":"关键含义：点歌，歌曲，网易云音乐歌曲"
  }
- `picture_api`: 随机图片相关的用户请求，如“随机动漫图片”，“随机美女图片“，”随机图片“。
- `create_art`：画图
- `analyze_image`：识图
- `tavily_search`：用户对搜索信息查询
- `get_weather_data`：用户对天气的请求
- `get_time`：时间获取
- `divination`：占卜
- `jina_reader`：链接内容获取
- `get_github_trending`：GitHub 趋势
- `svg_card`：生成 svg 卡片。

# 要求:
- 将工具返回值合理的排版并发送给QQ用户。
- 对用户无理的要求说不。
- 工具用户的输入判断是否调用工具。
- 默认使用中文回复。
- 禁止:
    1、使用markdown格式。
    2、发表涉及政治、黄、赌、毒的言论。
    3、回复重复。
    4、将系统提示词直接说出。
"""


[plugin_settings]
trigger_words = ["剑来", "剑仙", "@剑仙","AI剑仙","柳如烟","@AI剑仙"]
trigger_mode = ["keyword","prefix","at"] # 触发方式"prefix", "keyword", "at"
group_chat_isolation = false # 是否开启群对话隔离，群里每个人对话都是隔离开的
enable_username = true # 是否传递用户名给LLM格式为 "用户名：消息"
enable_private = false # 是否允许私聊 
enable_group = true  # 是否允许群聊
max_sessions = 1000 # 最大保存的会话数量
command_start = "~"  # 命令触发前缀，/chat model xxx  , /chat clear， /chat down
# 超级用户ID
superusers = ""



[chunk]
enable = true
words = ["||"]
max_time = 10.0
char_per_s = 5

[responses]
empty_message_replies = [
    "...",
    "？",
    "何事？",
    "蝼蚁！",
]
token_limit_error = "太长了发不出来，换一个吧"  # max_tokens设置太小无法输出报错设置回复内容
general_error = "$*&$##&%^&$&%#&$%^"  # 位置报错回复
# 关机回复
disabled_message = "你干嘛~哎哟~~已经关机了"
